---
  - name: Install Java 17 on debian
    ansible.builtin.include_tasks: debian.yml
    when: ansible_os_family == "Debian"

  - name: Install Java 17 on rpm
    ansible.builtin.include_tasks: rpm.yml
    when: ansible_os_family == "RedHat"
