---
# tasks file for jmeter
- name: install the jmeter for the RPM_based system
  ansible.builtin.include_tasks: install_rpm.yml
  when: ansible_os_family == "RedHat"

- name: install the jmeter for the Debian_based system
  ansible.builtin.include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"
