---
  - name: Upgrage java in debian
    ansible.builtin.include_tasks: debian.yml
    when: ansible_os_family == "Debian"

  - name: Upgrade java in rpm
    ansible.builtin.include_tasks: rpm.yml
    when: ansible_os_family == "RedHat"
