---
# Install MySQL server on Debian-based systems
- name: Install MySQL server on Debian
  apt:
    name: mysql-server
    state: present
  become: yes
  when: ansible_os_family == "Debian"

# Ensure MySQL service is started on Debian-based systems
- name: Start MySQL service on Debian
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes
  when: ansible_os_family == "Debian"
  


# Install MySQL server on RedHat-based systems
- name: Install MySQL server on RedHat
  yum:
    name: mysql-server
    state: present
  become: yes
  
# Ensure MySQL service is started on RedHat-based systems
- name: Start MySQL service on RedHat
  service:
    name: mysqld
    state: started
    enabled: yes
  become: yes
  when: ansible_os_family == "RedHat"
  
# Add yum repo of my sql workbench
- name: Add repo of mysql workbench
  ansible.builtin.yum_repository:
    name: mysql
    description: mysql workbench install
    baseurl: https://repo.mysql.com/yum/mysql-community/fc/19/x86_64/
    gpgcheck: yes
    gpgkey: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
    enabled: yes

- name: Install mysql
  ansible.builtin.yum:
    name: mysql-workbench
    state: present
