---
# tasks file for openssl
- ansible.builtin.include_tasks: install_rpm.yml
  when: ansible_os_family == "RedHat"

- ansible.builtin.include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"
