- name: Verify Python installation
  ansible.builtin.command: "python{{ python_version }} --version"
  register: python_version_output
  become: yes

- name: Print Python version
  ansible.builtin.debug:
    msg: "Python version installed: {{ python_version_output.stdout }}"
